[versions]
compileSdk = "36"
minSdk = "26"
targetSdk = "36"
versionCode = "2"
versionName = "1.2"

agp = "8.10.1"
circleimageview = "3.1.0"
converterGson = "3.0.0"
coreSplashscreen = "1.0.1"
firebaseBom = "34.1.0"
flexbox = "3.0.0"
fragmentKtx = "1.8.8"
glide = "4.16.0"
glideTransformations = "4.3.0"
gson = "2.13.1"
hiltAndroid = "2.56.2"
kotlin = "2.0.21"

kotlinKsp = "2.0.21-1.0.27"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
kotlinxCoroutinesAndroid = "1.10.2"
ksp-glide = "4.16.0"
leakcanaryAndroid = "2.14"
loggingInterceptor = "4.12.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
multidex = "2.0.1"
navigationFragmentKtx = "2.8.9"
retrofit = "3.0.0"
roomKtx = "2.7.2"
swiperefreshlayout = "1.1.0"
timber = "5.0.1"
lifecycleProcess = "2.9.1"
googleServices = "4.4.3"
firebaseCrashlytics = "3.0.6"
googleCloudTranslate = "2.67.0"
desugaring = "2.1.5"
shimmer = "0.5.0"
appUpdateKtx = "2.1.0"
minsapAdsdk = "1.0.29"
lottie = "6.6.7"
uiUnitAndroid = "1.8.3"
coil = "3.0.0"
coilNetworkOkhttp = "3.0.0"
assetDeliveryKtx = "2.3.0"
navigationFragmentKtxVersion = "2.9.5"
navigationUiKtx = "2.9.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
asset-delivery-ktx = { module = "com.google.android.play:asset-delivery-ktx", version.ref = "assetDeliveryKtx" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil3-coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
google-cloud-translate = { module = "com.google.cloud:google-cloud-translate", version.ref = "googleCloudTranslate" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-transformations = { module = "jp.wasabeef:glide-transformations", version.ref = "glideTransformations" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
ksp-glide = { module = "com.github.bumptech.glide:ksp", version.ref = "ksp-glide" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
minsap-adsdk = { module = "com.minsap.ad:minsap-adsdk", version.ref = "minsapAdsdk" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
androidx-ui-unit-android = { group = "androidx.compose.ui", name = "ui-unit-android", version.ref = "uiUnitAndroid" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt-android-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }


